apiVersion: skaffold/v2beta3
kind: Config

build:
  artifacts:
  - image: gcr.io/dkyt-275519/dykt-api-image
    context: backend
  local: {}

deploy:
  helm:
    releases:
      - name: dev
        chartPath: charts
        values:
          image: gcr.io/dkyt-275519/dykt-api-image

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: gcr.io/dkyt-275519/dykt-api-image
        context: backend
        docker:
          buildArgs:
            ENV: production
            MONGO_URI: mongodb://dev-mongodb:27017/dykt-api
        sync:
          manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.js'
            dest: .
#  - name: staging
#    activation:
#      - command: staging
#    build:
#      artifacts:
#        - image: gcr.io/dkyt-275519/dykt-api-image
#          context: backend
#          docker:
#            buildArgs:
#              ENV: staging
#          sync:
#            manual:
#              # Sync all the javascript files that are in the src folder
#              # with the container src folder
#              - src: 'src/**/*.js'
#                dest: .