apiVersion: skaffold/v2beta3
kind: Config

build:
  artifacts:
  - image: enterprise-client
    context: enterprise-client
  - image: landing-page
    context: landing-page
  - image: timesheet-client
    context: timesheet-client

deploy:
  helm:
    releases:
      - name: dev
        chartPath: charts
        values:
          image: enterprise-client

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: enterprise-client
        context: enterprise-client
        docker:
          buildArgs:
            ENV: production
        sync:
          manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.js'
            dest: .
#  - name: staging
#    activation:
#      - command: staging
#    build:
#      artifacts:
#        - image: gcr.io/dkyt-275519/dykt-api-image
#          context: backend
#          docker:
#            buildArgs:
#              ENV: staging
#          sync:
#            manual:
#              # Sync all the javascript files that are in the src folder
#              # with the container src folder
#              - src: 'src/**/*.js'
#                dest: .